name: 'update stars'
on:
  schedule:
    -
      cron: "0 0 * * *"
jobs:
  build:
    name: 'stargazed'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'checkout'
        uses: actions/checkout@v1
      -
        name: 'install node'
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      -
        name: 'install stargazed'
        run: 'npm install --global stargazed'
      -
        name: 'stargazed commit'
        run:
          stargazed --username  "angga759" --token ${{ secrets.GITHUB_TOKEN }} --repo "my-star-repository" --message "☆ ～('▽^人)" --sort
